/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BookATable: typeof import('./components/menuTabsWindow/BookATable.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    OrderOnline: typeof import('./components/menuTabsWindow/OrderOnline.vue')['default']
    ProductCardA: typeof import('./components/productCard/ProductCardA.vue')['default']
    ProductCardB: typeof import('./components/productCard/ProductCardB.vue')['default']
    ProductCardC: typeof import('./components/productCard/ProductCardC.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./components/SearchItem.vue')['default']
  }
}
